{% set name = "jsons" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ramonhagenaars/jsons/archive/v{{ version }}.tar.gz
  sha256: feb89d0ab290e9a3c4759ef0a9a7ffe181628cc52775e741d4e0423a5b5ec539

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - typish >=1.9.2

test:
  imports:
    - jsons
  requires:
    - pip
    - dataclasses
    - python >= 3.6
    - pytest
  source_files:
    - tests
    - test_resources
  commands:
    - pip check
    - pytest --pyargs jsons .

about:
  home: https://github.com/ramonhagenaars/jsons/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Turn Python objects into dicts or (json)strings
  description: Turn Python objects into dicts or (json)strings No changes required to your objects Easily customizable and extendable
  doc_url: https://jsons.readthedocs.io/
  dev_url: https://github.com/ramonhagenaars/jsons/

extra:
  recipe-maintainers:
    - ngodber
